// Theme config for the four maps. Visuals are based on the official QQ Speed map concept art:
// City 11 (tower bridge, SPEED airship, mascot balloons, blue boost arrows), Aegean Romance (white walls and blue domes, flagstone roads, bougainvillea),
// Pharaoh's Pyramid (purple/white checkered start, winged sphinxes, sun-disc gateway), Snow Adventure (cedars, trophy, hot-air balloons, grandstand banners)
export const MAPS = [
  {
    id: 'city',
    name: 'City 11',
    tag: 'Classic Race · 11 Corners',
    desc: 'A tower bridge over the river, skyscrapers and blue neon boost pads: a fast-paced city circuit.',
    layout: 'city',
    sky: { top: '#2f7fe0', horizon: '#cfeaff', bottom: '#8fb8d8', sun: [-0.45, 0.62, -0.55], sunColor: '#fff4dc', sunI: 2.6 },
    hemi: ['#d6ecff', '#6f8a5a', 1.1],
    fog: ['#cfe6fb', 380, 2300],
    ground: 'grass',
    groundTint: '#ffffff',
    water: { color: '#1f7fd1', deep: '#0b3f7a', y: -1.6 },
    track: {
      road: 'asphalt', wall: 'city', curbA: '#e53935', curbB: '#ffffff', deckColor: 0xc7c3d6,
      checkerA: '#101010', checkerB: '#ffffff', boostColor: '#27c7ff',
      boostPads: [{ at: [-120, -151] }, { at: [205, -8] }, { at: [-262, 8], lat: -4 }, { at: [-262, 8], lat: 4 }],
      shoulder: { width: 7, tex: 'plaza' },
    },
    isBridge: (x, z, y) => Math.abs(z) < 80 && y > 1.5,
    bgm: 0,
  },
  {
    id: 'aegean',
    name: 'Aegean Romance',
    tag: 'Hill Town Climb · Hairpin Chain',
    desc: 'An island town of white walls and blue domes, where flagstone roads wind uphill and hairpins test back-to-back drifts.',
    layout: 'aegean',
    sky: { top: '#3a8ee6', horizon: '#e4f3ff', bottom: '#9cc6e6', sun: [0.5, 0.55, -0.45], sunColor: '#fff1d6', sunI: 2.7 },
    hemi: ['#e8f4ff', '#a39a7a', 1.15],
    fog: ['#dcefff', 420, 2400],
    ground: 'aegean',
    groundTint: '#ffffff',
    water: { color: '#1a8fd8', deep: '#07477f', y: -1.0 },
    track: {
      road: 'flagstone', wall: 'aegean', curbA: '#2f7fd8', curbB: '#ffffff', deckColor: 0xe9e4d8,
      checkerA: '#1d4f9e', checkerB: '#ffffff', boostColor: '#ffd23a',
      boostPads: [{ at: [-60, -178] }, { at: [120, 115] }],
      tunnels: [{ from: [-296, 128], to: [-340, 10] }],
      shoulder: { width: 5, tex: 'plaza' },
      tunnelOuter: 0xf2eee6,
    },
    bgm: 1,
  },
  {
    id: 'egypt',
    name: "Pharaoh's Pyramid",
    tag: 'Desert Jumps · Temple Tunnel',
    desc: 'Race through the temple of the pharaohs, fly off the dune ramps and nail a landing boost as you touch down!',
    layout: 'egypt',
    sky: { top: '#3b86d8', horizon: '#fbe7c4', bottom: '#e9c99a', sun: [0.35, 0.5, 0.6], sunColor: '#fff0cf', sunI: 3.0 },
    hemi: ['#fff1d8', '#c49a5a', 1.05],
    fog: ['#f3dfbd', 420, 2500],
    ground: 'sand',
    groundTint: '#ffffff',
    water: { color: '#23a3b8', deep: '#0d5a6a', y: -0.6, local: true },
    track: {
      road: 'sandstone', wall: 'egypt', curbA: '#5b3f9e', curbB: '#f3e3b5', deckColor: 0xd9b77a,
      checkerA: '#5b3f9e', checkerB: '#ffffff', boostColor: '#ff9a1f',
      boostPads: [{ at: [2, -60] }, { at: [300, 20] }],
      tunnels: [{ from: [0, -250], to: [0, -150] }],
      tunnelOuter: 0xd6b274,
    },
    bgm: 2,
  },
  {
    id: 'snow',
    name: 'Snow Adventure',
    tag: 'Figure-8 Overpass · Ice Tunnel',
    desc: 'Cedar forests and ice tunnels, weaving over and under a figure-8 overpass while the grandstand cheers you home.',
    layout: 'snow',
    sky: { top: '#3f86d6', horizon: '#e2f0ff', bottom: '#c9ddf2', sun: [-0.3, 0.45, 0.7], sunColor: '#ffffff', sunI: 2.4 },
    hemi: ['#eef6ff', '#9fb4cc', 1.25],
    fog: ['#e3eefb', 350, 2200],
    ground: 'snow',
    groundTint: '#ffffff',
    track: {
      road: 'plate', wall: 'snow', curbA: '#c62828', curbB: '#ffffff', deckColor: 0x9fb0c8,
      checkerA: '#101010', checkerB: '#ffffff', boostColor: '#39c5ff',
      boostPads: [{ at: [-60, -200] }, { at: [-20, 120] }],
      tunnels: [{ from: [-110, -52], to: [-235, -40] }],
      tunnelOuter: 0xdfeaf6,
      roadMetal: 0.35, roadRough: 0.55,
    },
    isBridge: (x, z, y) => y > 5.5,
    snowfall: true,
    bgm: 3,
  },
  {
    id: 'neon',
    name: 'Neon Tokyo',
    tag: 'Night Street Circuit · 90° Corners',
    desc: 'A midnight street race between glowing towers, under neon arches, through right-angle corners.',
    layout: 'neon',
    sky: { top: '#070b24', horizon: '#3b2a78', bottom: '#15122e', sun: [0.3, 0.6, -0.5], sunColor: '#b8c6ff', sunI: 1.1 },
    hemi: ['#6a78c8', '#2a2440', 1.05],
    fog: ['#2a2358', 300, 1900],
    ground: 'grass',
    groundTint: '#ffffff',
    track: {
      road: 'asphalt', wall: 'city', curbA: '#ff2d95', curbB: '#ffffff', deckColor: 0x4a4f63,
      checkerA: '#101010', checkerB: '#ffffff', boostColor: '#ff2d95',
      boostPads: [{ at: [0, -200] }, { at: [300, -10] }, { at: [-150, 380] }],
      shoulder: { width: 6, tex: 'plaza' },
    },
    bgm: 0,
  },
  {
    id: 'bay',
    name: 'Harbor Bay',
    tag: 'Hill Climbs · Twin Bridges',
    desc: 'Cross the channel on red suspension bridges, then climb and dive through the painted hills.',
    layout: 'bay',
    sky: { top: '#3d7fd6', horizon: '#ffd9b0', bottom: '#9ab8d8', sun: [-0.6, 0.35, -0.4], sunColor: '#ffe2b8', sunI: 2.5 },
    hemi: ['#ffe9d0', '#6f8a5a', 1.1],
    fog: ['#f1dcc4', 380, 2300],
    ground: 'grass',
    groundTint: '#ffffff',
    water: { color: '#1f6fb5', deep: '#0b3a6a', y: -1.6 },
    track: {
      road: 'asphalt', wall: 'city', curbA: '#c0362c', curbB: '#ffffff', deckColor: 0x8a8f99,
      checkerA: '#101010', checkerB: '#ffffff', boostColor: '#27c7ff',
      boostPads: [{ at: [-200, -154] }, { at: [-430, -20] }],
      shoulder: { width: 5, tex: 'plaza' },
    },
    isBridge: (x, z, y) => Math.abs(x) < 72 && y > 2.5,
    bgm: 1,
  },
  {
    id: 'dune',
    name: 'Dune Metropolis',
    tag: 'Flat-Out Straights · Skyline Jump',
    desc: 'A sunset sprint past gold glass towers and palm-lined boulevards, with a jump on the north side.',
    layout: 'dune',
    sky: { top: '#3a4fb0', horizon: '#ffb070', bottom: '#e9c99a', sun: [0.7, 0.18, 0.3], sunColor: '#ffc27a', sunI: 2.6 },
    hemi: ['#ffe0c0', '#c49a5a', 1.05],
    fog: ['#f4c79a', 420, 2500],
    ground: 'sand',
    groundTint: '#ffffff',
    track: {
      road: 'asphalt', wall: 'egypt', curbA: '#8e24aa', curbB: '#ffffff', deckColor: 0xd9b77a,
      checkerA: '#8e24aa', checkerB: '#ffffff', boostColor: '#ff9a1f',
      boostPads: [{ at: [0, -258] }, { at: [40, 180] }, { at: [-400, 90] }],
      shoulder: { width: 5, tex: 'plaza' },
    },
    bgm: 2,
  },
];

export const MODES = [
  { id: 'speed', name: 'Speed Race', desc: 'Drift charge, mini boosts, double boosts: pure skill' },
  { id: 'item', name: 'Item Race', desc: 'Missiles, bananas, angels, magnets, nitro' },
];
